# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Test

on: [push, pull_request]

env:
  TERRAFRAME_CI_CACHE_DIR: .cache/TerraFrame

jobs:
  test:
    strategy:
      matrix:
        python: ['3.12', '3.13']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Cache data
      uses: actions/cache@v3
      with:
          path: .cache/mypkg
          key: TerraFrame-data-${{ hashFiles('**/pyproject.toml') }}
    - name: Install test dependencies
      run: pip install .[test]
    - name: Run tests
      env:
        PYTEST_PLATFORM: ${{ matrix.platform }}
        PYTEST_PYTHON: ${{ matrix.python }}
      run: pytest
